[functions]
  directory = "src/server/functions"
  included_files = ["data/*"]

[build]
  command = "npm run build"
  functions = "src/server/functions/"

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/blog"
  status = 200

[[redirects]]
  from = "/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/products"
  to = "/.netlify/functions/product"
  status = 200

[[redirects]]
  from = "/product/*"
  to = "/.netlify/functions/product"
  status = 200
