[functions]
  directory = "src/server/functions"
  included_files = ["data/*"]

[build]
  command = "npm run build"
  functions = "src/server/functions/"

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/blog"
  status = 200
